Fix #127 allow passing cmd as an array for exec_in_pods
chaostoolkit/chaostoolkit-kubernetes pull request #129
Opened 2021-12-14 13:35 UTC by kpk-pl

Allow to pass a list of cmd arguments to exec_in_pods. Keep supporting cmd as string which is split and trimmed.
Added two test cases to validate cmd is passed as expected.

Also it bothered me a bit that some testcases to exec_in_pods were copy-pasted so I went ahead and trimmed them down getting rid of unnecessary complexity and params in a separate commit. I can remove that if you don't agree with the refactor.

2021-12-14 14:27 UTC, Lawouach requested changes
A bunch of minor changes and it'll be fine.

2021-12-14 14:27 UTC, Lawouach commented on CHANGELOG.md
> +
We prefer that PRs do not set the versions. Simply remove these lines and it'll be fine :)

2021-12-14 14:27 UTC, Lawouach commented on chaosk8s/__init__.py
> +__version__ = "0.26.2"
don't change the version here :)

2021-12-16 13:18 UTC, kpk-pl commented
@Lawouach Removed the commit with the version changes

2021-12-16 16:13 UTC, Lawouach requested changes
Great. Could you add a changelog entry too please?

2021-12-16 16:32 UTC, kpk-pl commented
> Great. Could you add a changelog entry too please?

Done. Also fixed failing UTs on older Python

2021-12-16 16:43 UTC, Lawouach approved these changes

2021-12-16 16:44 UTC, merged